syntax on

" allow plugins by file type (required for plugins!)
filetype plugin on
filetype indent plugin on  " required since nixpkgs b3abdc9534a675da2aa7631d505a5f71ef30ecfa

" tabs and spaces handling
set expandtab
set tabstop=4
set softtabstop=4
set shiftwidth=4

" Sin esta línea el backspace anda muy mal en nixos
" Es el default en el vimrc estándar
set backspace=indent,eol,start
set encoding=utf-8

" always show status bar
set laststatus=2

" Mostrar resultados de búsqueda a medida que se introduce el patrón
set incsearch

set number

" mostrar números de línea relativos a la posición del cursor
set relativenumber

" when scrolling, keep cursor 3 lines away from screen border
set scrolloff=3

set mouse=a
set ttymouse=sgr  " Para que funcione el scroll con st

" autocompletion of files and commands behaves like shell
" (complete only the common part, list the options that match)
" TODO: chequar alternativas
set wildmode=list:longest 

" better backup, swap and undos storage
set directory=~/.vim/dirs/tmp     " directory to place swap files in
set backup                        " make backup files
set backupdir=~/.vim/dirs/backups " where to put backup files
set undofile                      " persistent undos - undo after you re-open the file
set undodir=~/.vim/dirs/undos
"set viminfo+=n~/.vim/dirs/viminfo
set viminfo='100,<50,s10,h,n~/.vim/dirs/viminfo

if !isdirectory(&backupdir)
    call mkdir(&backupdir, "p")
endif
if !isdirectory(&directory)
    call mkdir(&directory, "p")
endif
if !isdirectory(&undodir)
    call mkdir(&undodir, "p")
endif

" Tamaño del historial
set history=500 

" Timeout para mappings y otros
set timeoutlen=300

set ignorecase
" Si el patrón de búsqueda contiene mayúsculas -> set noignorecase temporal
set smartcase

" :w!! guarda con fichero con sudo
cabbrev w!! w !sudo tee "%"

map tt :tabnew 

" Mostrar el mismo fichero en dos paneles distintos
map ,s :only<CR>:vs<CR><C-l>

" Habilitar/deshabilitar resaltado de resultados de búsqueda
nnoremap <F4> :set hlsearch!<CR>

" Invertir ^ y 0
nnoremap ^ 0
nnoremap 0 ^

" Expandir %% a la ruta del directorio actual
cnoremap <expr> %% getcmdtype() == ':' ? expand('%:h').'/' : '%%'

" Mejor forma de moverse entre ventanas
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" Algún plugin mapea la tecla enter en modo normal a C-a, quito esto
" unmap <CR>

" Invertir "" y "+
" Uso bastante la función de usar el registro del clipboard ("+). Si a los
" mappings que los utilizan no se les pasa ningún registro utilizan el unnamed
" ("") por lo que es poco probable que lo utilice de forma explícita.
" También mapeo "' a "* (el registro del clipboard de X11)
nnoremap "" "+
nnoremap "+ ""
vnoremap "" "+
vnoremap "+ ""
nnoremap "' "*
vnoremap "' "*

" configuración NERDTree
let NERDTreeIgnore = ['\.pyc$', '\.pyo$']
map <F3> :NERDTreeToggle<CR>
nmap ,t :NERDTreeFind<CR>
"

" Configuración de FZF
nmap ,e :GFiles<CR>
nmap ,E :Files<CR>
nmap ,b :Buffers<CR>
nmap ,m :History<CR>
nmap ,h :History:<CR>
nmap ,T :Tags<CR>

nnoremap <F5> :ALEToggle<CR>
nnoremap <F6> :SignifyToggle<CR>

" python: replace default indent for line continuations (from 8 to 4 spaces)
let g:pyindent_open_paren = 'shiftwidth()'
let g:pyindent_continue = 'shiftwidth()'

" tab length exceptions on some file types
autocmd FileType c setlocal noexpandtab
autocmd FileType cpp setlocal noexpandtab

" Make panes resize when host window is resized
" Taken from https://vi.stackexchange.com/questions/201/make-panes-resize-when-host-window-is-resized
autocmd VimResized * wincmd =

let &t_Co = 256
set background=dark
colorscheme solarized

" Custom highlight para signify
highlight DiffAdd           cterm=bold ctermbg=none ctermfg=119
highlight DiffDelete        cterm=bold ctermbg=none ctermfg=167
highlight DiffChange        cterm=bold ctermbg=none ctermfg=227
highlight SignifySignAdd    cterm=bold ctermbg=237  ctermfg=119
highlight SignifySignDelete cterm=bold ctermbg=237  ctermfg=167
highlight SignifySignChange cterm=bold ctermbg=237  ctermfg=227

set nomodeline
